# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data C104
description: Data C104 at UC Berkeley
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'http://data104.org'
staff_email: 'datac104@berkeley.edu'
course_department: dsus

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - CONTRIBUTING.md
  - tmp/
  - spec/
  - docs/
  - node_modules/

# Heading settings
lecture:
  time: "3:00 - 4:00"
  location:
      name: "Dwinelle 155"
      link: ""
# heading_links:
#   - text:
#     url:
#   - text:
#     url:
# lecture_prefix: "csXXX-sp25-lec"

# Theme settings
theme: just-the-docs
# color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Dark Mode:
    - '#'
  Source Code on GitHub:
    - 'https://github.com/ds-104/datac104-website'
footer_content: true

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/staff/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

color_scheme: wider

callouts:
  warning:
    title: Warning
    color: yellow
  story: # CS 161 custom config for story
    title: Story
    color: blue
  example: # CS 161 custom config for proj2
    title: Example
    color: blue
  question: # CS 161 custom config for proj2
    title: Design Question
    color: green

# For copy button on code
enable_copy_code_button: true

# CS 188 custom config variable
# Set this to true at the start of semesters to show a warning on the homepage
under_construction: false

# Set this to true to show a warning telling people on the waitlist to check FAQs
waitlist_warning: false

# Set this to true if discussion times are uncertain (populates on calendar.md)
discussions_under_construction: false

# Set this to true to archive the semester
outdated: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-jupyter-notebook
